[build]
target = "index.html"

[serve]
address = "127.0.0.1"
port = 8081
open = false

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
  "-c",
  "tailwindcss --input style/tailwind.css --output style/out.css --minify"
]
